# Java Gradle CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - gradle-cache

      # Gradle Wrapper
      - run:
          name: Gradle Version
          command: |
            sudo chmod +x gradlew
            ./gradlew --version
      - run:
          name: Build
          command: |
            export GIT_COMMIT_DESC=$(git log --format=%B -n 1 $CIRCLE_SHA1)
            ./gradlew clean build --stacktrace
      - when:
          condition:
            equal: [ 14-release, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Publish
                command: |
                  export GIT_COMMIT_DESC=$(git log --format=%B -n 1 $CIRCLE_SHA1)
                  ./gradlew upload --info --stacktrace
                # ./gradlew publishGprPublicationToGitHubPackagesRepository

      - store_artifacts:
          path: ./build/libs

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache
