name: Beta
on:
  push:
    branches:
      - '14-develop'

jobs:
  build-beta:
    name: Build Beta
    uses: xfl03/MCCustomSkinLoader/.github/workflows/common.yml@14-develop
    with:
      type: Beta
      publish-task: uploadBeta
    secrets: inherit