name: beta
on:
  push:
    branches:
      - '14-develop'

jobs:
  build-beta:
    uses: xfl03/MCCustomSkinLoader/.github/workflows/common.yml@14-develop
    with:
      type: Beta
      publish-task: uploadBeta