name: canary
on:
  push:
    branches:
      - '15-develop'

jobs:
  build-canary:
    uses: xfl03/MCCustomSkinLoader/.github/workflows/common.yml@15-develop
    with:
      type: Canary
      publish-task: uploadCanary
    secrets: inherit