name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '14-develop'
      - '15-develop'

jobs:
  build-pull-request:
    name: Build Pull Request
    uses: xfl03/MCCustomSkinLoader/.github/workflows/common.yml@14-develop
    with:
      type: PullRequest