name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    name: Build Release
    uses: xfl03/MCCustomSkinLoader/.github/workflows/common.yml@14-develop
    with:
      type: Release
      publish-task: upload
    secrets: inherit